import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  git,
  figma,
  docker,
  MovieAPP,
  itiEcommerce,
  weather,
  Quize,
  JSEcreommece,
  carrent,
  jobit,
  tripguide,
  threejs,
  codeAlpha,
  ITI,
  Route,
  ECPC,
  Bootstrap,
  SQL,
  hourefimage,
  Huson,
  summit,
  Afro,
  Alto,
  APTF,
  IZITechs,
  MindScope,
  Arkan,
  Sadad,
  Elshams,
  InnoCode,
  Peg,
  qutoof,
  elbasira,
  abdelhamid,
  almanzoor,
  maharaedara,
  mediaReef,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
    title_ar: "من أنا",
  },
  {
    id: "work",
    title: "Work",
    title_ar: "المشاريع",
  },
  {
    id: "contact",
    title: "Contact",
    title_ar: "تواصل معي",
  },
];

export const getLocalizedNavLinks = (lang = 'en') => {
  const isAr = lang === 'ar';
  return navLinks.map((link) => ({
    id: link.id,
    title: isAr && link.title_ar ? link.title_ar : link.title,
  }));
};

const services = [
  {
    title: "Frontend Developer",
    title_ar: "مطور واجهات أمامية",
    icon: web,
  },
  {
    title: "Backend Developer",
    title_ar: "مطور خوادم وقواعد بيانات",
    icon: web,
  },
];

export const getLocalizedServices = (lang = 'en') => {
  const isAr = lang === 'ar';
  return services.map((s) => ({
    ...s,
    title: isAr && s.title_ar ? s.title_ar : s.title,
  }));
};

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "Bootstrap",
    icon: Bootstrap,
  },
  {
    name: "TypeScript",
    icon: typescript,
  },
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Three JS",
    icon: threejs,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "figma",
    icon: figma,
  },
  {
    name: "docker",
    icon: docker,
  },
  {
    name: "SQL Server",
    icon: SQL,
  },
];

const experiences = [
  {
    title: "Full-Stack Developer",
    title_ar: "مطور برمجيات متكامل – Full Stack",
    company_name: "PEG-Engineering Consulting",
    company_name_ar: "بي إي جي للاستشارات الهندسية (PEG)",
    icon: Peg,
    iconBg: "#E6DEDD",
    date: "Nov 2025 – Present",
    date_ar: "نوفمبر 2025 – حتى الآن",
    points: [
      "Built full-stack enterprise ERP and HRMS platforms using ASP.NET Core, DDD, Entity Framework, and SQL Server.",
      "Engineered responsive, bilingual React.js and Next.js, Angular frontend architectures with TypeScript and Tailwind.",
      "Integrated real-time SignalR, RabbitMQ messaging, secure REST APIs, and role-based access control.",
    ],
    points_ar: [
      "تطوير وبناء منصات ERP وإدارة موارد بشرية (HRMS) مؤسسية شاملة باستخدام ASP.NET Core و DDD و Entity Framework و SQL Server.",
      "هندسة واجهات أمامية متجاوبة وثنائية اللغة بتقنيات React.js و Next.js و Angular مع TypeScript و Tailwind CSS.",
      "تكامل الأنظمة اللحظي باستخدام SignalR وقوائم رسائل RabbitMQ وتأمين واجهات REST API مع التحكم الدقيق في الصلاحيات (RBAC).",
    ],
  },
  {
    title: "Frontend Developer",
    title_ar: "مطور واجهات أمامية – Frontend",
    company_name: "Inno Code",
    company_name_ar: "إينو كود (Inno Code)",
    icon: InnoCode,
    iconBg: "#383E56",
    date: "Jun 2025 – Oct 2025",
    date_ar: "يونيو 2025 – أكتوبر 2025",
    points: [
      "Building modern SaaS applications in AI, e-commerce, and internal ERP tools using React and Next.js.",
      "Contributed to UI consistency and reusable components using TypeScript and Tailwind CSS.",
      "Worked closely with Product, UX, and AI teams to deliver scalable, performant frontend systems.",
    ],
    points_ar: [
      "بناء تطبيقات SaaS حديثة في مجالات الذكاء الاصطناعي والتجارة الإلكترونية وأنظمة الـ ERP الداخلية باستخدام React و Next.js.",
      "تطوير مكونات واجهة مستخدم قابلة لإعادة الاستخدام وضمان التناسق البصري باستخدام TypeScript و Tailwind CSS.",
      "التعاون الوثيق مع فرق تصميم تجربة المستخدم والذكاء الاصطناعي لتسليم واجهات أمامية مرنة وعالية الأداء.",
    ],
  },
  {
    title: "Frontend Developer",
    title_ar: "مطور واجهات أمامية – Frontend",
    company_name: "IZI Techs",
    company_name_ar: "آي زد آي تكس (IZI Techs)",
    icon: IZITechs,
    iconBg: "#E6DEDD",
    date: "Jan 2024 – Jul 2025",
    date_ar: "يناير 2024 – يوليو 2025",
    points: [
      "Created SEO-friendly, responsive applications with 30% improvement in user engagement metrics.",
      "Implemented performance optimizations resulting in 40% faster page load times across all company applications.",
      "Engineered pixel-perfect designs using React.js and Tailwind CSS, achieving 98% design-to-implementation accuracy.",
      "Collaborated with UX/UI teams to develop accessible interfaces compliant with WCAG 2.1 standards.",
    ],
    points_ar: [
      "تطوير تطبيقات متجاوبة ومتوافقة مع معايير السيو (SEO) محققاً زيادة بنسبة 30% في تفاعل المستخدمين.",
      "تطبيق تحسينات متقدمة في الأداء أسفرت عن تسريع وقت تحميل الصفحات بنسبة 40% عبر جميع تطبيقات الشركة.",
      "تنفيذ تصميمات فائقة الدقة بـ React.js و Tailwind CSS بدقة مطابقة للتصاميم بلغت 98%.",
      "التعاون مع فرق الـ UX/UI لتطوير واجهات ميسرة الوصول ومتوافقة كلياً مع معايير WCAG 2.1.",
    ],
  },
  {
    title: "Frontend Intern",
    title_ar: "متدرب واجهات أمامية – Frontend Intern",
    company_name: "CodeAlpha",
    company_name_ar: "كود ألفا (CodeAlpha)",
    icon: codeAlpha,
    iconBg: "#383E56",
    date: "Jun 2024 – Aug 2024",
    date_ar: "يونيو 2024 – أغسطس 2024",
    points: [
      "Completed various tasks using HTML, CSS, Bootstrap, JavaScript, ReactJS, and TypeScript.",
      "Developed projects including a to-do app, calendar, music app, and real-time social media platform.",
      "Enhanced practical skills in front-end development and collaborated effectively with team members.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
    points_ar: [
      "إنجاز مهام ومشاريع عملية متنوعة باستخدام HTML و CSS و Bootstrap و JavaScript و ReactJS و TypeScript.",
      "تطوير تطبيقات متعددة تشمل تطبيق مهام، تقويم، تطبيق موسيقى، ومنصة تواصل اجتماعي في الوقت الفعلي.",
      "تعزيز المهارات العملية في تطوير الواجهات الأمامية والتعاون الفعال مع أعضاء الفريق.",
      "المشاركة في مراجعات الأكواد وتقديم تعليقات واقتراحات بنّاءة لتحسين جودة الكود.",
    ],
  },
  {
    title: "ReactJS Intern",
    title_ar: "متدرب تطوير – React.js",
    company_name: "ITI",
    company_name_ar: "معهد تكنولوجيا المعلومات (ITI)",
    icon: ITI,
    iconBg: "#E6DEDD",
    date: "Jul 2024 – Aug 2024",
    date_ar: "يوليو 2024 – أغسطس 2024",
    points: [
      "Learn HTML5, CSS3, JS, Bootstrap, and React.js.",
      "Daily intensive workshops and e-commerce final graduation project.",
    ],
    points_ar: [
      "دراسة وتطبيق HTML5 و CSS3 و JavaScript و Bootstrap و React.js.",
      "ورش عمل يومية مكثفة ومشروع تخرج نهائي لمتجر تجارة إلكترونية متكامل.",
    ],
  },
  {
    title: "Full-Stack Development Diploma",
    title_ar: "دبلومة تطوير الويب المتكامل – Full Stack",
    company_name: "Route",
    company_name_ar: "أكاديمية راوت (Route)",
    icon: Route,
    iconBg: "#383E56",
    date: "Dec 2022 – Nov 2023",
    date_ar: "ديسمبر 2022 – نوفمبر 2023",
    points: [
      "Front-end: HTML, CSS, Bootstrap, JavaScript, jQuery, and React.js.",
      "Back-end: SQL Server, C#, OOP, Linq, Entity Framework, MVC, Web API, Design Patterns, and Agile methodology.",
      "Development of highly responsive, web-based user interfaces.",
      "Developed flexible, well-structured project architectures and APIs.",
      "Translated complex designs, wireframes, and business requirements into clean, high-quality code.",
    ],
    points_ar: [
      "الواجهات الأمامية: HTML، CSS، Bootstrap، JavaScript، jQuery، و React.js.",
      "الأنظمة الخلفية: SQL Server، C#، OOP، Linq، Entity Framework، MVC، Web API، Design Patterns، ومنهجية Agile.",
      "تطوير واجهات مستخدم تفاعلية عالية الاستجابة والأداء.",
      "بناء معمارية برمجية متماسكة وتطوير واجهات برمجة التطبيقات (APIs) الداعمة لها.",
      "تحويل التصاميم والنماذج ومتطلبات العمل إلى حلول برمجية بأكواد عالية الجودة.",
    ],
  },
  {
    title: "Problem Solving",
    title_ar: "حل المشكلات والخوارزميات (Problem Solving)",
    company_name: "SFE ICPC",
    company_name_ar: "SFE ICPC",
    icon: ECPC,
    iconBg: "#E6DEDD",
    date: "Aug 2021 – Jun 2022",
    date_ar: "أغسطس 2021 – يونيو 2022",
    points: [
      "Advanced competitive programming in C++.",
      "Data structures, algorithms, and complexity optimization.",
    ],
    points_ar: [
      "البرمجة التنافسية المتقدمة بلغة C++.",
      "هياكل البيانات والخوارزميات وتحسين التعقيد الحسابي (Data Structures & Algorithms).",
    ],
  },
];

export const getLocalizedExperiences = (lang = 'en') => {
  const isAr = lang === 'ar';
  return experiences.map((exp) => ({
    ...exp,
    title: isAr && exp.title_ar ? exp.title_ar : exp.title,
    company_name: isAr && exp.company_name_ar ? exp.company_name_ar : exp.company_name,
    date: isAr && exp.date_ar ? exp.date_ar : exp.date,
    points: isAr && exp.points_ar ? exp.points_ar : exp.points,
  }));
};

const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Mohamed proved me wrong.",
    testimonial_ar:
      "كنت أعتقد أنه من الصعب جداً تطوير منصة بهذا المستوى من الأناقة والسرعة، لكن محمد تجاوز كل التوقعات باحترافية استثنائية.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Mohamed does.",
    testimonial_ar:
      "نادراً ما تجد مطوراً يهتم بنجاح المشروع وأدق التفاصيل التقنية وتجربة المستخدم كما يفعل محمد عادل.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Mohamed optimized our website, our traffic and conversion rates increased significantly!",
    testimonial_ar:
      "بعد أن قام محمد بتحسين أداء موقعنا وسرعته، ارتفعت حركة الزوار ومعدلات التحويل بشكل ملموس وممتاز!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    id: "reef-pmo",
    name: "Reef – Enterprise PMO & Media Platform",
    name_ar: "منصة برنامج ريف – المنظومة المؤسسية للإعلام وإدارة المشاريع (PMO)",
    tagline: "Saudi Sustainable Rural Development Ecosystem with Next.js Media Hub, Angular PMO Portal & ASP.NET Core CQRS Backend",
    tagline_ar: "منظومة تنمية ريفية مستدامة بالمملكة تشمل منصة إعلامية بـ Next.js وبوابة حوكمة المشروعات بـ Angular ونظام CQRS بـ ASP.NET Core",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2025 – Present",
    year_ar: "2025 – حتى الآن",
    client: "Saudi Ministry of Environment, Water & Agriculture (MEWA)",
    client_ar: "وزارة البيئة والمياه والزراعة السعودية (برنامج ريف)",
    category: "fullstack",
    description: "An enterprise full-stack ecosystem built for the Saudi Sustainable Rural Agricultural Development Program (Reef PMO). The system comprises two synchronized platforms: a modern bilingual media and knowledge hub built with Next.js App Router for public awareness, and an advanced enterprise PMO portal built with Angular & PrimeNG to govern the entire workflow of engineering consultants and contractors. Backed by ASP.NET Core Web API with Clean Architecture, CQRS (MediatR), RabbitMQ messaging, and SignalR real-time communications.",
    description_ar: "منظومة برمجية متكاملة لبرنامج التنمية الريفية الزراعية المستدامة (ريف السعودية). تتكون من منصتين متزامنتين: منصة إعلامية ومعرفية بـ Next.js App Router لتعريف الجمهور والتوعية، وبوابة إدارة المشروعات والمقاولين المؤسسية بـ Angular و PrimeNG لحوكمة مهام الاستشاريين والمقاولين. متصلة بخدمات ASP.NET Core Web API بمعمارية Clean Architecture ونمط CQRS وقنوات RabbitMQ والاتصال الحي SignalR.",
    features: [
      "Public Media & Knowledge Hub built with Next.js App Router, Turbopack & Tailwind CSS",
      "Enterprise PMO Portal for Consultant & Contractor Workflow Governance and Task Execution",
      "Financial Statement & Extractor Approval Engine (المستخلصات المالية) with Verification Lifecycles",
      "Dynamic Arabic (RTL) Interface with PrimeNG & Tailwind UI Component Architecture",
      "Comprehensive HR Subsystem with 33+ Entities and Granular Role-Based Access Control (RBAC)",
      "Multi-Version Analytics Dashboards Tracking Agricultural Sector KPIs and Contractor Performance",
      "Real-Time Chat & Activity Stream using SignalR with RabbitMQ Asynchronous Message Queues",
      "Automated Executive Reporting Engine generating dynamic PDF/Excel Progress Manifests",
    ],
    features_ar: [
      "بوابة المعرفة والمنصة الإعلامية بـ Next.js App Router و Turbopack مع تهيئة كاملة للسيو",
      "بوابة إدارة مشروعات (PMO) لمتابعة تدفق أعمال الاستشاريين والمقاولين واعتماد الإنجازات",
      "محرك تدقيق واعتماد المستخلصات المالية للمقاولين ومسارات التحقق المتعددة",
      "واجهة عربية متكاملة (RTL) متوافقة مع PrimeNG وتصميم Tailwind UI المؤسسي",
      "نظام إدارة الموارد البشرية (HR) يضم 33+ كياناً مع نظام صلاحيات دقيق (RBAC)",
      "لوحات مؤشرات أداء تفاعلية لمتابعة مؤشرات القطاعات الزراعية وسرعة الإنجاز",
      "نظام محادثات وتنبيهات فورية عبر SignalR وقوائم رسائل RabbitMQ غير المتزامنة",
      "نظام تقارير تنفيذية مؤتمت لاستخراج ملخصات الإنجاز بملفات PDF و Excel تفاعلية",
    ],
    architecture: [
      "ASP.NET Core Web API built with Clean Architecture, CQRS pattern, and MediatR handlers",
      "Angular enterprise frontend with PrimeNG, Angular Material, and reactive RxJS state pipelines",
      "Next.js App Router for lightning-fast public media content rendering and SEO optimization",
      "Microsoft SQL Server relational database with Entity Framework Core & Dapper optimizations",
      "RabbitMQ distributed message broker coordinating background tasks and notification dispatching",
      "SignalR persistent WebSocket channels for real-time collaboration and approval notifications",
    ],
    architecture_ar: [
      "خدمات ASP.NET Core Web API بمعمارية Clean Architecture ونمط CQRS وموزعات MediatR",
      "واجهة Angular المؤسسية مع PrimeNG ومكتبة Angular Material ومسارات RxJS التفاعلية",
      "Next.js App Router لسرعة فائقة في معالجة المحتوى وتجربة تصفح فورية",
      "قاعدة بيانات SQL Server مع تحسينات Entity Framework Core و Dapper للاستعلامات المعقدة",
      "وسيط رسائل RabbitMQ لتنسيق المهام الخلفية وتدفق الإشعارات الموزعة",
      "قنوات SignalR عبر WebSocket لتحديثات سير العمل والموافقات اللحظية",
    ],
    tags: [
      { name: "ASP.NET Core", color: "blue-text-gradient" },
      { name: "CQRS", color: "green-text-gradient" },
      { name: "Clean Architecture", color: "pink-text-gradient" },
      { name: "Angular", color: "orange-text-gradient" },
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "SignalR", color: "green-text-gradient" },
      { name: "RabbitMQ", color: "pink-text-gradient" },
    ],
    image: mediaReef,
    source_code_link: "https://github.com",
    LiveDemo: "https://reefpmo.com/",
    isPrivate: true,
  },
  {
    id: "hosoun-academy",
    name: "Hosoun Academy",
    name_ar: "أكاديمية حصون التعليمية",
    tagline: "Comprehensive Educational Platform for Online Learning, Live Sessions & Book Sales",
    tagline_ar: "منصة تعليمية متكاملة للتعلم الإلكتروني، الحصص التفاعلية المباشرة وبيع الكتب",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2024 – 2025",
    year_ar: "2024 – 2025",
    client: "Hosoun Academy",
    client_ar: "أكاديمية حصون",
    category: "fullstack",
    description: "A comprehensive educational platform offering modern learning experiences including recorded courses, live online classes, teaching jobs, educational articles, and digital book sales. Features secure payment gateway, teacher dashboard for course management, and admin panel for performance monitoring.",
    description_ar: "منصة تعليمية تفاعلية شاملة تقدم دورات مسجلة وحصصاً افتراضية مباشرة عبر الإنترنت، مع نظام توظيف للمعلمين، مدونة مقالات تعليمية، ومتجر رقمي لبيع الكتب المدرسية. تشتمل على بوابات دفع إلكترونية آمنة، لوحة تحكم للمعلم لإدارة الحصص، ولوحة تحكم للمسؤولين لمتابعة الأداء والإيرادات.",
    features: [
      "Recorded Courses & Interactive Live Online Classrooms",
      "Teacher Dashboard for Course Management & Scheduling",
      "Admin Control Panel for Performance Monitoring & Analytics",
      "Digital Book Sales & Educational Article Publishing",
      "Secure Online Payment Gateway Integration",
    ],
    features_ar: [
      "دورات تعليمية مسجلة وفصول افتراضية تفاعلية حية للطلاب",
      "لوحة تحكم للمعلمين لإدارة المقررات، المواعيد ومتابعة الطلاب",
      "لوحة إدارة شاملة لمراقبة الأداء الإداري والمالي للسنتر التعليمي",
      "متجر بيع الكتب الرقمية ونشر المقالات والأبحاث التعليمية",
      "تكامل مع بوابات الدفع الإلكتروني الآمنة",
    ],
    architecture: [
      "React.js single-page architecture with Bootstrap responsive design",
      "ASP.NET Core Web API & MVC backend services",
      "Microsoft SQL Server database with Entity Framework ORM",
      "Role-based access control for students, teachers, and administrators",
    ],
    architecture_ar: [
      "تطبيق صفحة واحدة بواجهة React.js وتصميم متجاوب مع Bootstrap",
      "خدمات خوادم ASP.NET Core Web API و MVC الخلفية",
      "قاعدة بيانات Microsoft SQL Server مع Entity Framework ORM",
      "نظام تحكم في الصلاحيات مخصص للطلاب والمعلمين والإدارة",
    ],
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Bootstrap", color: "green-text-gradient" },
      { name: "Web API", color: "pink-text-gradient" },
      { name: "MVC", color: "orange-text-gradient" },
      { name: "SQL", color: "blue-text-gradient" },
    ],
    image: Huson,
    source_code_link: "https://github.com",
    LiveDemo: "https://hosoun.com",
    isPrivate: true,
  },
  {
    id: "qutoof-organic",
    name: "Qutoof Organic Platform & CMS Dashboard",
    name_ar: "منصة قطوف أورجانيك ولوحة تحكم الـ CMS",
    tagline: "Bilingual Organic Food & Beverage Marketplace with Real-Time Content Management CMS",
    tagline_ar: "متجر منتجات عضوية ثنائي اللغة مع لوحة إدارة محتوى حية ولحظية",
    role: "Frontend Developer & UI Engineer",
    role_ar: "مطور واجهات أمامية ومهندس تجربة مستخدم",
    year: "2025 – 2026",
    year_ar: "2025 – 2026",
    client: "Qutoof Organic",
    client_ar: "قطوف أورجانيك",
    category: "frontend",
    description: "Developed a modern bilingual organic food & beverage platform and administrative CMS dashboard. Built dynamic product showcases (coffee, tea, herbs, and healthy drinks), full RTL support, interactive nationwide delivery locator across Egypt, customer reviews, and comprehensive content management tools for real-time catalog control.",
    description_ar: "تطوير منصة رقمية ثنائية اللغة لمنتجات الأغذية والمشروبات العضوية ولوحة تحكم CMS لإدارة المحتوى. تتضمن كتالوج منتجات تفاعلي (قهوة، شاي، أعشاب، مشروبات صحية)، دعم كامل للغة العربية (RTL)، خريطة تفاعلية لتغطية التوصيل بجميع محافظات مصر، نظام تقييمات العملاء، وأدوات لإدارة المنتجات والبنرات لحظياً.",
    features: [
      "Diverse Product Showcase & Dynamic Catalog (Coffee, Tea, Herbs & Healthy Drinks)",
      "Full-Featured Administrative CMS Dashboard to control products, content, and banners",
      "Complete Arabic RTL & English layout support with responsive typography",
      "Interactive Nationwide Delivery & Regional Distribution Locator across Egypt",
      "Customer Reviews, Testimonials & Trust Validation System",
      "High-Performance Image Gallery with Lazy Loading & Mobile-First Optimization",
    ],
    features_ar: [
      "كتالوج منتجات ديناميكي وتصنيفات تفاعلية للقهوة والشاي والأعشاب والمشروبات",
      "لوحة تحكم إدارية (CMS) كاملة للتحكم في المنتجات والمحتوى والبنرات الترويجية",
      "دعم كامل ومتقن للاتجاهين العربي (RTL) والإنجليزي (LTR) بخطوط متناسقة",
      "محدد تفاعلي لمناطق التوصيل ومنافذ التوزيع في كافة محافظات مصر",
      "نظام تقييمات العملاء وآراء المشترين لتعزيز الموثوقية",
      "معرض صور عالي الكفاءة مع تحميل كسول (Lazy Loading) وتوافق تام مع الهواتف",
    ],
    architecture: [
      "Next.js App Router with Server-Side & Static Generation for optimal SEO",
      "Tailwind CSS with responsive design system and RTL-first layout classes",
      "Context API for global state management and theme / language localization",
      "RESTful API integration for real-time catalog fetching and content updates",
    ],
    architecture_ar: [
      "Next.js App Router مع توليد المحتوى الثابت (SSG) لتحقيق أقصى درجات السيو والأداء",
      "Tailwind CSS مع نظام تصميم مخصص وفئات داعمة للـ RTL بالكامل",
      "Context API لإدارة الحالة العامة وتبديل اللغة والمظهر",
      "ربط متكامل مع واجهات برمجة التطبيقات (RESTful API) لتحديث المحتوى الفوري",
    ],
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
      { name: "i18n", color: "pink-text-gradient" },
      { name: "Context", color: "orange-text-gradient" },
    ],
    image: qutoof,
    source_code_link: "https://github.com",
    LiveDemo: "https://qutooforganic.com/",
    isPrivate: true,
  },
  {
    id: "elbasira-law-firm",
    name: "Al-Basira Law Firm Website",
    name_ar: "موقع شركة البصيرة الرشيدة للمحاماة",
    tagline: "Corporate Legal Services Platform with Arabic RTL & English Internationalization",
    tagline_ar: "منصة استشارات قانونية ثنائية اللغة متوافقة مع الاتجاه العربي ومصممة بأعلى معايير الهوية المؤسسية",
    role: "Frontend Developer & UI Engineer",
    role_ar: "مطور واجهات أمامية ومهندس تجربة مستخدم",
    year: "2025 – 2026",
    year_ar: "2025 – 2026",
    client: "Al-Basira Al-Rashida Law Firm",
    client_ar: "شركة البصيرة الرشيدة للمحاماة والاستشارات القانونية",
    category: "frontend",
    description: "Developed a modern corporate website for Al-Basira Al-Rashida law firm in Saudi Arabia with full Arabic (RTL) and English support. Features interactive legal service showcases, animated achievement statistics, client testimonials slider, FAQ accordions, appointment booking, and dynamic consultation request forms.",
    description_ar: "تطوير موقع مؤسسي متكامل لشركة البصيرة الرشيدة للمحاماة في المملكة العربية السعودية باللغتين العربية والإنجليزية. يتضمن استعراضاً للخدمات القضائية، عدادات إحصائية متحركة للإنجازات ونسب النجاح، شريط لآراء العملاء، قسم الأسئلة الشائعة بنظام الأكورديون، ونماذج حجز الاستشارات وتحديد المواعيد.",
    features: [
      "Arabic (RTL) & English Corporate Legal Platform with Modern Typography",
      "Interactive Legal Services Showcase with Detailed Consultation Views",
      "Animated Statistics & Achievements Counter (Cases, Sessions, Success Rate)",
      "Client Testimonials Slider with Star Ratings & Real-Time Feedback",
      "Dynamic Appointment Booking & Consultation Request Forms with Validation",
      "Accordion-Style FAQ System with Smooth Collapse Transitions",
    ],
    features_ar: [
      "منصة قانونية ثنائية اللغة (عربي RTL وإنجليزي) بخطوط وهوية سعودية أنيقة",
      "عرض تفاعلي للخدمات القانونية والاستشارية والتوكيلات القضائية",
      "عدادات رقمية متحركة لأبرز الإنجازات (القضايا، الجلسات، ونسب النجاح)",
      "سلايدر متحرك لآراء وتوصيات الموكلين مع تقييمات النجوم",
      "نماذج متطورة لحجز المواعيد والاستشارات القانونية مع التحقق من صحة البيانات",
      "نظام أكورديون تفاعلي للأسئلة الشائعة مع حركات انسيابية ناعمة",
    ],
    architecture: [
      "React frontend architecture with modular component composition",
      "Tailwind CSS styling with customized Saudi legal corporate color palette",
      "Framer Motion for animated section reveals, counters, and testimonial sliders",
      "Semantic HTML5 & WCAG 2.1 accessibility compliance",
    ],
    architecture_ar: [
      "معمارية مكونات React قابلة لإعادة الاستخدام بأعلى جودة برمجية",
      "تصميم Tailwind CSS بهوية قانونية متناسقة وتباين لوني ملائم",
      "مكتبة Framer Motion لتأثيرات الظهور الحركية للسكاشن والعدادات",
      "التزام كامل بمعايير الوصولية WCAG 2.1 والوسوم الدلالية HTML5",
    ],
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
      { name: "i18n", color: "pink-text-gradient" },
      { name: "Framer-Motion", color: "orange-text-gradient" },
    ],
    image: elbasira,
    source_code_link: "https://github.com",
    LiveDemo: "https://elbasira.net/ar",
    isPrivate: true,
  },
  {
    id: "abdelhamid-law-firm",
    name: "Abdelhamid Rohim Law Firm & Legal CMS Portal",
    name_ar: "مؤسسة عبد الحميد رحيم للمحاماة وبوابة الـ CMS",
    tagline: "Bilingual Corporate Legal Advisory Platform with Admin CMS Dashboard, Visitor Analytics, Document Storage & Client Inquiry Messaging Engine",
    tagline_ar: "منصة قانونية استشارية ثنائية اللغة مع لوحة تحكم إدارية متقدمة، تحليلات الزوار، تخزين الملفات القضائية ونظام متابعة استفسارات الموكلين",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2025 – 2026",
    year_ar: "2025 – 2026",
    client: "Abdelhamid Rohim Law Firm",
    client_ar: "مؤسسة عبد الحميد رحيم للمحاماة والاستشارات القانونية",
    category: "fullstack",
    description: "A comprehensive bilingual corporate legal platform and administrative CMS dashboard built for Abdelhamid Rohim Law Firm (Cairo, Egypt). In addition to client-facing practice showcases and consultation booking, the platform features a secure back-office admin dashboard equipped with real-time visitor analytics, centralized legal file storage for case documents and evidence, and an inquiry messaging workflow to follow up on consultations and dispatch responses to clients.",
    description_ar: "منصة استشارات قانونية متكاملة ولوحة تحكم إدارية CMS لمؤسسة عبد الحميد رحيم للمحاماة (القاهرة). بالإضافة إلى استعراض التخصصات القانونية وحجز المواعيد للمراجعين، تشتمل المنصة على لوحة تحكم خلفية آمنة مزودة بإحصائيات حية لعدد الزوار ومصادر الزيارات، مستودع سحابي لحفظ وثائق ومستندات القضايا، ونظام مراسلات متكامل لمتابعة استفسارات العملاء والرد عليها.",
    features: [
      "Administrative Control Dashboard for Centralized Firm & Website Management",
      "Real-Time Visitor Traffic & Engagement Analytics to Track User Inflow & Sources",
      "Secure Legal Document & File Storage System for Case Files, Contracts & Media",
      "Client Inquiry Messaging Center to Track, Follow Up & Respond to Legal Requests",
      "Bilingual Legal Advisory Platform with Arabic (RTL) & English Layouts",
      "Interactive Hero Video Experience & 4-Video Consultation Showcase Carousel",
      "Specialized Legal Practice Portals (Personal Status, Civil, Criminal, Corporate, Privacy)",
      "Dynamic WhatsApp Consultation Dispatcher with Structured Message Formatting",
      "Online Appointment Booking Management System (/Appointment)",
      "18-Slide Courtroom Achievements, Credentials & Media Gallery",
      "Animated Key Performance Metrics (19+ Years Experience, 100% Client Satisfaction)",
      "Client Testimonials Slider with Verified Case Reviews & Ratings",
    ],
    features_ar: [
      "لوحة تحكم إدارية مركزية للتحكم الشامل في محتوى الموقع والمكتب القانوني",
      "نظام تحليلات لحظي لتتبع حركة الزوار والمشاهدات ومصادر الزيارات",
      "نظام تخزين آمن للمستندات والملفات القضائية وعقود الموكلين مع الأرشفة",
      "مركز مراسلات لمتابعة استفسارات الاستشارات القانونية والرد على الموكلين",
      "منصة استشارية ثنائية اللغة مع دعم كامل للاتجاهين العربي والإنجليزي",
      "تجربة فيديو تفاعلية وسلايدر يضم 4 مقاطع مرئية للاستشارات القانونية",
      "بوابات تخصصية (الأحوال الشخصية، المدني، الجنائي، الشركات، الملكية الفكرية)",
      "زر تحويل الاستشارات الفورية عبر واتساب مع رسائل مهيأة تلقائياً",
      "نظام متكامل لإدارة وحجز المواعيد والاستشارات القانونية (/Appointment)",
      "معرض وسائط وإنجازات محاكم يضم 18 شريحة من القضايا والشهادات",
      "مؤشرات إنجاز متحركة (خبرة تزيد عن 19 عاماً، نسبة رضا 100%)",
      "شريط تفاعلي لآراء الموكلين وتقييمات القضايا الناجحة",
    ],
    architecture: [
      "ASP.NET Core MVC architecture with structured admin controllers, Razor views & API endpoints",
      "Role-based authentication & authorization securing the administrative back-office dashboard",
      "Optimized file storage pipeline with MIME-type validation and categorized document repositories",
      "Visitor telemetry and analytics logging engine providing live traffic metrics and trends",
      "Bilingual RTL/LTR localization engine with instant culture switching",
      "WhatsApp Web/API deep-linking integration for instant consultation routing",
      "SEO-optimized semantic markup with OpenGraph, Twitter Cards & meta tags",
    ],
    architecture_ar: [
      "معمارية ASP.NET Core MVC مع وحدات تحكم مخصصة للوحة الإدارة وواجهات API",
      "نظام مصادقة وتفويض مبني على الأدوار (RBAC) لحماية لوحة الإدارة",
      "خط معالجة لتخزين الملفات مع التحقق الصارم من أنواع الملفات وحمايتها",
      "محرك تسجيل وتحليل حركة الزوار لتوفير تقارير وبيانات حية",
      "محرك تعريب ثنائي اللغة RTL/LTR مع تبديل لحظي للثقافة",
      "ربط متقدم مع واجهات واتساب لتوجيه المراجعين للاستشارة القانونية",
      "بنية سيو متقدمة مع وسوم OpenGraph و Twitter Cards لتصدر محركات البحث",
    ],
    tags: [
      { name: "ASP.NET MVC", color: "blue-text-gradient" },
      { name: "C#", color: "green-text-gradient" },
      { name: "Dashboard / CMS", color: "pink-text-gradient" },
      { name: "File Storage", color: "orange-text-gradient" },
      { name: "Analytics", color: "blue-text-gradient" },
      { name: "RTL-Arabic", color: "green-text-gradient" },
    ],
    image: abdelhamid,
    source_code_link: "https://github.com",
    LiveDemo: "https://abdalhmidrohim.com/",
    isPrivate: true,
  },
  {
    id: "almanzoor-architecture",
    name: "Al Manzoor Architecture & Urban Design Studio",
    name_ar: "استوديو المنظور الشامل للهندسة المعمارية والتصميم الحضري",
    tagline: "Bilingual Luxury Architectural Portfolio with Next.js App Router, Synced Dual Swiper Sliders & Editorial Case Studies",
    tagline_ar: "بورتفوليو معماري فاخر ثنائي اللغة بـ Next.js App Router وسلايدر مزدوج متزامن بـ Swiper ودراسات حالة تحريرية",
    role: "Frontend Developer & UI Engineer",
    role_ar: "مطور واجهات أمامية ومهندس تجربة مستخدم",
    year: "2025 – 2026",
    year_ar: "2025 – 2026",
    client: "Al Manzoor Alshamel (UK & KSA)",
    client_ar: "المنظور الشامل (لندن والمملكة العربية السعودية)",
    category: "frontend",
    description: "Architected a high-end bilingual architectural portfolio and urban design studio platform for Al Manzoor Alshamel (UK & Riyadh, KSA). Features a fullscreen synchronized dual-swiper hero slider with miniature thumbnail preview navigation, split-letter typography animation engine, alternating editorial project showcases with oversized numbers (01-04), studio philosophy narrative, achievement metric counters (66+ projects), and full Arabic RTL / English LTR support.",
    description_ar: "بناء وتطوير منصة بورتفوليو معمارية فاخرة واستوديو للتصميم الحضري لشركة المنظور الشامل (المملكة المتحدة والرياض). يتميز الموقع بسلايدر هيدر مزدوج متزامن بشاشة كاملة مع شريط مصغر للصور، حركات نصوص متطورة بالأحرف المقسمة، استعراض تحريري للمشاريع بأرقام ضخمة متناوبة (01-04)، سرد لفلسفة الاستوديو المعمارية، وعدادات للمشاريع المنجزة (66+ مشروعاً) مع دعم كامل للعربية والإنجليزية.",
    features: [
      "Bilingual Architecture Portfolio with Seamless Arabic (RTL) & English Layouts",
      "Fullscreen Hero Slider with Synchronized Thumbnail Track & Active Slide Indicators",
      "Split-Letter Typography Animation Engine with Staggered Character Reveals",
      "Asymmetric Editorial Project Showcase (Le Building, The Ripple, Pearls Hotel, Yanbu Oasis)",
      "Multi-Aspect Ratio Image Composition (3:4 Detail Previews + 4:5 Master Context Views)",
      "Studio Achievements & Metric Counters (66 Total, 12 Completed, 20 Outgoing Projects)",
      "Responsive Layout with Custom Monochromatic Luxury Aesthetics & Outfit/Cairo Typography",
    ],
    features_ar: [
      "بورتفوليو معماري ثنائي اللغة بتوافق كامل مع الاتجاه العربي (RTL) والإنجليزي",
      "سلايدر ملء الشاشة متزامن مع شريط مصغرات متحرك ومؤشرات تفاعلية",
      "محرك حركات نصوص مقسمة (Split-Letter) بحركات تدريجية للأحرف",
      "استعراض تحريري غير متماثل للمشاريع الرئيسية (لو بيلدينغ، ذا ريبل، فندق بيرلز، واحة ينبع)",
      "تكوين بصري بنسب أبعاد صور متعددة (3:4 للتفاصيل و 4:5 للمشاهد العامة)",
      "إحصائيات إنجازات الاستوديو (66 مشروعاً إجمالياً، 12 مكتملاً، 20 قيد التنفيذ)",
      "تصميم نخبوي متجاوب مع هوية بصرية فاخرة وأسلوب تايبوغرافي أنيق",
    ],
    architecture: [
      "Next.js App Router with React Server Components (RSC) & Turbopack for optimal performance",
      "Tailwind CSS custom design system tailored for minimalist luxury architecture",
      "Swiper.js dual-instance synchronized navigation between master hero slides and thumbnail strip",
      "CSS transform & opacity keyframe animations for directional scroll reveals and letter transitions",
      "Modular bilingual routing (/en and /ar) with localized metadata and semantic SEO markup",
    ],
    architecture_ar: [
      "Next.js App Router مع مكونات React Server Components (RSC) و Turbopack",
      "نظام تصميم مخصص بـ Tailwind CSS مصمم خصيصاً للمكاتب المعمارية الفاخرة",
      "مزامنة ذكية بين نسختي Swiper.js لسلايدر العرض وشريط المعاينة المصغر",
      "حركات تحويل وشفافية CSS دقيقة لظهور السكاشن وانتقالات الأحرف",
      "توجيه ثنائي اللغة معياري (/ar و /en) مع بيانات وصفية وسيو مخصص لكل لغة",
    ],
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
      { name: "Swiper.js", color: "pink-text-gradient" },
      { name: "i18n", color: "orange-text-gradient" },
      { name: "TypeScript", color: "blue-text-gradient" },
    ],
    image: almanzoor,
    source_code_link: "https://github.com",
    LiveDemo: "https://almanzoor-web.vercel.app/en",
    isPrivate: true,
  },
  {
    id: "mahara-edara",
    name: "Maharah Edara – Portfolio & CMS Dashboard",
    name_ar: "منصة مهارة إدارة ولوحة تحكم الـ CMS",
    tagline: "End-to-End Enterprise Advisory Platform with ASP.NET Core DDD Architecture & Next.js CMS Dashboard",
    tagline_ar: "منظومة استشارات مؤسسية متكاملة بمعمارية ASP.NET Core DDD ولوحة تحكم Next.js لإدارة المحتوى",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2025 – 2026",
    year_ar: "2025 – 2026",
    client: "Maharah Edara (Saudi Arabia & Egypt)",
    client_ar: "شركة مهارة إدارة للاستشارات (السعودية ومصر)",
    category: "fullstack",
    description: "An enterprise-grade, end-to-end full-stack platform built with ASP.NET Core following Domain-Driven Design (DDD) principles on the backend and Next.js / TypeScript on the frontend. Developed both the client-facing corporate portal and the administrative CMS dashboard for Maharah Edara (Riyadh, Saudi Arabia). Engineered 8+ content management modules allowing complete administrative control over consulting services, feasibility studies, projects, articles, team members, partners, and service requests with JWT auth, token refresh, and robust server-side processing.",
    description_ar: "منصة مؤسسية شاملة (Full-Stack) مبنية على خوادم ASP.NET Core بتطبيق مبادئ التصميم الموجه بالمجال (DDD) و Clean Architecture، وواجهة Next.js بـ TypeScript. تم بناء كلٍ من الموقع المؤسسي الموجه للعملاء ولوحة التحكم الإدارية CMS لشركة مهارة إدارة (الرياض). تشتمل على 8+ وحدات إدارة محتوى تتيح تحكماً إدارياً كاملاً في الخدمات الاستشارية، دراسات الجدوى، المشاريع السابقة، المقالات، فريق العمل، الشركاء، وطلبات الخدمات مع توثيق JWT وأمان فائق.",
    features: [
      "Full-Stack Architecture: Next.js Frontend seamlessly integrated with ASP.NET Core DDD Web APIs",
      "Comprehensive Administrative CMS Dashboard with 100% Real-Time Content Control",
      "8+ Dedicated Management Modules (Services, Feasibility Studies, Projects, Articles, Team, Partners, Requests)",
      "Domain-Driven Design (DDD) & Clean Architecture for high scalability and modular domain boundaries",
      "Bilingual Architecture with Arabic (RTL) Default & English (LTR) Localization",
      "Reusable UI System: Dynamic DataTables, FormWrappers, and TipTap Rich-Text Editor",
      "JWT Authentication with Silent Token Refresh, Session Auto-Logout & Role Route Guards",
      "Zod Schema Validation Integrated with React Hook Form for Type-Safe Forms",
      "Server-Side Pagination, Instant Filter Searches, and Fast Content Invalidation",
      "Interactive Service Request & Consultation Booking Workflow with Validation",
    ],
    features_ar: [
      "معمارية متكاملة Full-Stack: واجهة Next.js مرتبطة بخوادم ASP.NET Core DDD",
      "لوحة تحكم إدارية (CMS) متقدمة تتيح إدارة المحتوى بنسبة 100% في الوقت الفعلي",
      "8+ وحدات إدارة متخصصة (الخدمات، دراسات الجدوى، المشاريع، المقالات، الفريق، الشركاء، الطلبات)",
      "تطبيق نمط Domain-Driven Design و Clean Architecture لمرونة وتوسع الأنظمة المؤسسية",
      "بنية ثنائية اللغة متكاملة تدعم العربية (RTL) افتراضياً والإنجليزية (LTR)",
      "نظام واجهات قابلة لإعادة الاستخدام: جداول DataTables ديناميكية ومحرر نصوص TipTap غني",
      "توثيق JWT مع تجديد صامت للرموز (Silent Refresh) وتسجيل خروج تلقائي وحماية المسارات",
      "التحقق الصارم من البيانات باستخدام Zod Schema مدمجاً مع React Hook Form",
      "تقسيم صفحات خادمي (Server Pagination)، بحث فوري وإلغاء تخزين مؤقت سريع",
      "مسار متكامل لحجز الاستشارات وتقديم طلبات دراسات الجدوى مع التحقق الدقيق",
    ],
    architecture: [
      "ASP.NET Core Web API built with Domain-Driven Design (DDD), Clean Architecture & Repository pattern",
      "Microsoft SQL Server database with Entity Framework Core ORM and optimized relational indexing",
      "Next.js App Router with React, TypeScript, and Server-Side Rendering (SSR) for the frontend",
      "Tailwind CSS custom design system with RTL-first layout tokens and corporate styling",
      "Zod schema validation paired with React Hook Form for robust type-safe error handling",
      "TipTap rich-text editing engine with custom extensions for article and study publishing",
    ],
    architecture_ar: [
      "خوادم ASP.NET Core Web API مبنية بنمط DDD و Clean Architecture ونمط المستودعات (Repository)",
      "قاعدة بيانات SQL Server مع Entity Framework Core وفهارس علاقات محسنة",
      "Next.js App Router مع React و TypeScript وتقديم المحتوى من الخادم (SSR)",
      "نظام تصميم Tailwind CSS بمتغيرات RTL وهوية استشارية متزنة",
      "التحقق من المخططات بـ Zod مع React Hook Form لإدارة نماذج آمنة من الأخطاء",
      "محرر TipTap الغني لإضافة وتنسيق المقالات والدراسات التخصصية",
    ],
    tags: [
      { name: "ASP.NET Core", color: "blue-text-gradient" },
      { name: "DDD", color: "green-text-gradient" },
      { name: "Next.js", color: "pink-text-gradient" },
      { name: "TypeScript", color: "orange-text-gradient" },
      { name: "SQL Server", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
    ],
    image: maharaedara,
    source_code_link: "https://github.com",
    LiveDemo: "https://maharaedara.com/ar/home",
    isPrivate: true,
  },
  {
    id: "mind-scope",
    name: "Mind-Scope AI Platform",
    name_ar: "منصة مايند سكوب للذكاء الاصطناعي (Mind-Scope AI)",
    tagline: "Multilingual AI Assistant Platform with Multi-Model Generation Tools",
    tagline_ar: "منصة مساعد ذكاء اصطناعي متعددة اللغات مع أدوات توليد متطورة",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2025",
    year_ar: "2025",
    client: "Mind-Scope AI",
    client_ar: "Mind-Scope AI",
    category: "fullstack",
    description: "Developed a comprehensive AI assistant platform with multilingual support (English & Arabic) and RTL layout capabilities. Implemented multiple AI generation tools including text chat, code generation, email composition, and AI image creation. Built responsive UI with custom theme switching between light/dark modes with consistent styling across components.",
    description_ar: "تطوير منصة مساعد ذكاء اصطناعي متعددة اللغات (العربية والإنجليزية) تدعم واجهة اليمين إلى اليسار (RTL). تشتمل على أدوات توليد متعددة بالذكاء الاصطناعي كالدردشة النصية، كتابة الأكواد، صياغة رسائل البريد الإلكتروني، وتوليد الصور. واجهة متجاوبة مع تبديل سلس بين الوضعين الداكن والفاتح.",
    features: [
      "Bilingual AI Assistant Platform with English & Arabic RTL capabilities",
      "Multi-Tool AI Suite: Text Chat, Code Generation, and Email Composition",
      "AI Image Generation and Visual Asset Processing",
      "Custom Dark / Light Theme Engine with Persistent State",
      "Responsive UI with High-Performance Micro-Animations",
    ],
    features_ar: [
      "منصة مساعد ذكاء اصطناعي ثنائية اللغة بدعم كامل للعربية (RTL) والإنجليزية",
      "حزمة أدوات ذكاء اصطناعي: محادثة نصية، توليد أكواد، وصياغة الرسائل",
      "توليد الصور بالذكاء الاصطناعي ومعالجة الوسائط المرئية",
      "محرك تبديل المظهر (Dark / Light) مع حفظ تفضيلات المستخدم",
      "واجهة مستخدم متجاوبة مع حركات تفاعلية فائقة السرعة",
    ],
    architecture: [
      "Next.js App Router for serverless API handling and lightning-fast frontend",
      "Tailwind CSS with custom CSS variables for seamless dark/light theme switching",
      "i18next for comprehensive English and Arabic translation & RTL orientation",
      "Sal.js and SweetAlert2 for rich notification flows and scroll reveals",
    ],
    architecture_ar: [
      "Next.js App Router لمعالجة الواجهات وواجهات برمجة التطبيقات بدون خوادم",
      "Tailwind CSS مع متغيرات CSS لتبديل سلس بين الثيمات",
      "i18next للتعريب الشامل باللغتين العربية والإنجليزية",
      "مكتبات Sal.js و SweetAlert2 لتدفقات الإشعارات وظهور السكاشن",
    ],
    tags: [
      { name: "next.js", color: "blue-text-gradient" },
      { name: "tailwindCSS", color: "green-text-gradient" },
      { name: "i18next", color: "green-text-gradient" },
      { name: "sal.js", color: "pink-text-gradient" },
      { name: "sweetalert2", color: "orange-text-gradient" },
    ],
    image: MindScope,
    source_code_link: "https://github.com",
    LiveDemo: "https://mind-scope.ae/",
    isPrivate: true,
  },
  {
    id: "horuf-platform",
    name: "Horuf Platform",
    name_ar: "منصة حروف التعليمية",
    tagline: "Educational Single-Page Application for Teacher & Academy Management",
    tagline_ar: "تطبيق صفحة واحدة متقدم لإدارة وعرض المعلمين في المراكز التعليمية",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2024",
    year_ar: "2024",
    client: "Hrouf Academy",
    client_ar: "أكاديمية حروف",
    category: "fullstack",
    description: "Hrouf Academy is a single-page application (SPA) developed with React, designed for managing and displaying Teachers in Teaching center called Hrouf Academy. It includes an advanced search feature to help users find their desired Teachers.",
    description_ar: "تطبيق صفحة واحدة (SPA) مطور بتقنية React لإدارة واستعراض المعلمين في مركز حروف التعليمي. يتضمن ميزات بحث وفلترة متقدمة لمساعدة الطلاب وأولياء الأمور في العثور على المعلم المناسب ومتابعة الجداول.",
    features: [
      "Single-Page Application (SPA) with High-Performance React Architecture",
      "Dynamic Teacher Search, Filter & Profile Showcase System",
      "Admin Management Dashboard for Teaching Centers",
      "RESTful ASP.NET Web API Integration with SQL Server Database",
    ],
    features_ar: [
      "تطبيق صفحة واحدة (SPA) عالي الأداء مبني بـ React",
      "نظام بحث متقدم وفلترة تفاعلية لملفات المعلمين",
      "لوحة تحكم إدارية للمراكز التعليمية لتنظيم الكادر التدريسي",
      "ربط متكامل مع خدمات ASP.NET Web API وقواعد بيانات SQL Server",
    ],
    architecture: [
      "React SPA with fast client-side routing and instant filtering",
      "Bootstrap responsive UI framework",
      "ASP.NET MVC & Web API for robust data layer",
      "SQL Server backend database",
    ],
    architecture_ar: [
      "واجهة React SPA بتوجيه سريع وفلترة بيانات لحظية",
      "تصميم متجاوب بالكامل باستخدام Bootstrap",
      "خوادم ASP.NET MVC و Web API لطبقة معالجة البيانات",
      "قاعدة بيانات SQL Server خلفية",
    ],
    tags: [
      { name: "react", color: "blue-text-gradient" },
      { name: "Bootstrap", color: "green-text-gradient" },
      { name: "Web API", color: "pink-text-gradient" },
      { name: "MVC", color: "orange-text-gradient" },
      { name: "SQL", color: "blue-text-gradient" },
    ],
    image: hourefimage,
    source_code_link: "https://github.com/mohamed-badr555/Horuf-Platform",
    LiveDemo: "https://www.hrouf-academy.com/",
    isPrivate: false,
  },
  {
    id: "arkan-dental",
    name: "Arkan Dental Clinic Website & Dashboard",
    name_ar: "موقع وعيادات أركان لطب الأسنان ولوحة التحكم",
    tagline: "Bilingual Dental Healthcare Platform & Medical Content Management System",
    tagline_ar: "منصة رعاية صحية للأسنان ثنائية اللغة مع نظام إدارة محتوى طبي",
    role: "Frontend Developer",
    role_ar: "مطور واجهات أمامية",
    year: "2024 – 2025",
    year_ar: "2024 – 2025",
    client: "Arkan Dental Clinic",
    client_ar: "عيادات أركان لطب الأسنان",
    category: "frontend",
    description: "Developed bilingual dental clinic website & CMS dashboard using Next.js, TypeScript and RESTful integration. Built comprehensive content management system with TypeScript-based API integration for secure operations. Implemented responsive UI with internationalization support and dynamic image optimization.",
    description_ar: "تطوير موقع وعيادات أركان لطب الأسنان ولوحة تحكم CMS باستخدام Next.js و TypeScript. بناء نظام إدارة محتوى متكامل مع ربط واجهات برمجة التطبيقات بأعلى معايير الأمان، مع دعم تعدد اللغات وحجز المواعيد الطبية.",
    features: [
      "Bilingual (AR/EN) Dental Clinic Web Experience with Dynamic Internationalization",
      "Custom Content Management Dashboard for Medical Staff & Clinic Services",
      "TypeScript-Based RESTful API Integration with Strict Type Safety",
      "Optimized Image Handling, Patient Appointment Booking & Doctor Profiles",
    ],
    features_ar: [
      "تجربة ويب ثنائية اللغة (AR/EN) لعيادات الأسنان مع تعريب كامل",
      "لوحة تحكم CMS مخصصة لإدارة خدمات العيادة والكادر الطبي",
      "ربط كامل مع واجهات RESTful API مبنية بـ TypeScript بأمان تام",
      "معالجة وتحسين الصور، حجز مواعيد المرضى واستعراض الأطباء",
    ],
    architecture: [
      "Next.js App Router with TypeScript for type-safe frontend components",
      "Tailwind CSS for responsive medical design system",
      "Custom Context API for localization and dashboard session state",
      "Optimized next/image pipeline for fast load times on medical imagery",
    ],
    architecture_ar: [
      "Next.js App Router مع TypeScript لضمان موثوقية المكونات",
      "Tailwind CSS لنظام تصميم طبي متناسق ومتجاوب",
      "Context API مخصص للتعريب وإدارة جلسة لوحة التحكم",
      "تحسين صور الأطباء والحالات الطبية عبر next/image",
    ],
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
      { name: "i18n", color: "pink-text-gradient" },
      { name: "Context", color: "orange-text-gradient" },
    ],
    image: Arkan,
    source_code_link: "https://github.com",
    LiveDemo: "https://arkandental.com",
    isPrivate: true,
  },
  {
    id: "sadad-financial",
    name: "Sadad Financial Services Platform",
    name_ar: "منصة سداد للخدمات المالية والقروض",
    tagline: "Arabic Financial Services Platform with Dynamic Loan Tracking & Calculations",
    tagline_ar: "منصة خدمات مالية عربية بحسابات وأدوات تتبع ديناميكية للقروض",
    role: "Frontend Developer",
    role_ar: "مطور واجهات أمامية",
    year: "2024 – 2025",
    year_ar: "2024 – 2025",
    client: "Sadad Financial Services",
    client_ar: "سداد للخدمات المالية",
    category: "frontend",
    description: "Engineered a Next.js financial platform with app router architecture for Arabic loan payment services with dynamic routing. Implemented RTL-optimized UI using Tailwind CSS with animated components via Framer Motion for seamless user experience. Built content-driven system with dynamic article rendering, category-based navigation, and custom search functionality.",
    description_ar: "تطوير منصة مالية بـ Next.js App Router لخدمات سداد القروض مع توجيه ديناميكي. واجهة مخصصة للغة العربية (RTL) باستخدام Tailwind CSS مع مكونات متحركة عبر Framer Motion لتجربة مستخدم مريحة وحاسبات تمويلية دقيقة.",
    features: [
      "Next.js App Router Architecture with Dynamic Routing for Financial Portals",
      "RTL-Optimized UI Engineered with Tailwind CSS and Framer Motion",
      "Interactive Loan Payment Calculators & Financial Service Guides",
      "Content-Driven Dynamic Article Rendering and Search Functionality",
    ],
    features_ar: [
      "معمارية Next.js App Router مع مسارات ديناميكية للبوابات المالية",
      "واجهة عربية أصيلة مصممة بـ Tailwind CSS و Framer Motion",
      "حاسبات تمويلية تفاعلية لاحتساب أقساط القروض والخدمات",
      "نظام استعراض مقالات وإرشادات مالية ديناميكي مع بحث متقدم",
    ],
    architecture: [
      "Next.js App Router with dynamic SSR routes for financial articles",
      "Tailwind CSS RTL configuration for Arabic layout perfection",
      "Framer Motion for high-fidelity interactive animations",
      "Context-driven search and filter state management",
    ],
    architecture_ar: [
      "مسارات SSR ديناميكية في Next.js لعرض المقالات والخدمات",
      "تهيئة Tailwind CSS للاتجاه العربي للوصول لتناسق بصري تام",
      "Framer Motion لحركات وتفاعلات سلسة عالية الجودة",
      "إدارة حالة البحث والفلترة عبر Context API",
    ],
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
      { name: "Framer-Motion", color: "pink-text-gradient" },
      { name: "Context", color: "orange-text-gradient" },
    ],
    image: Sadad,
    source_code_link: "https://github.com",
    LiveDemo: "https://saddadqrod.com",
    isPrivate: true,
  },
  {
    id: "elshams-finishing",
    name: "Elshams Platform & CMS Dashboard",
    name_ar: "منصة الشمس للتشطيبات ولوحة تحكم المحتوى",
    tagline: "Bilingual Architectural Finishing Showcase with Dynamic Multimedia CMS",
    tagline_ar: "معرض تشطيبات معمارية ثنائي اللغة مع لوحة CMS لإدارة الوسائط والمشاريع",
    role: "Frontend Developer",
    role_ar: "مطور واجهات أمامية",
    year: "2024 – 2025",
    year_ar: "2024 – 2025",
    client: "Elshams Finishing",
    client_ar: "الشمس للتشطيبات والديكور",
    category: "frontend",
    description: "Engineered bilingual construction portfolio platform with Next.js App Router and TypeScript. Developed comprehensive dashboard for content management enabling dynamic project showcases, client testimonials, and multimedia galleries. Implemented responsive UI with internationalization (AR/EN), lazy-loaded YouTube integration, optimized image handling, and animated components using Framer Motion for enhanced user engagement.",
    description_ar: "تطوير بورتفوليو تشطيبات وديكور ثنائي اللغة بـ Next.js App Router و TypeScript مع لوحة تحكم CMS لإدارة المشاريع، آراء العملاء ومعارض الفيديو والصور بتقنيات تحميل كسول ومكونات متحركة بـ Framer Motion.",
    features: [
      "Bilingual Construction & Interior Finishing Portfolio with Next.js App Router",
      "Comprehensive CMS Dashboard for Dynamic Project & Gallery Management",
      "Lazy-Loaded YouTube Video Integration & Multimedia Showcase",
      "Animated Interactive Components with Framer Motion and Smooth Transitions",
    ],
    features_ar: [
      "بورتفوليو تشطيبات وديكور ثنائي اللغة بـ Next.js App Router",
      "لوحة تحكم CMS شاملة لإدارة المشاريع وصور الأعمال المنفذة",
      "تكامل مع مقاطع يوتيوب بتقنيات التحميل الكسول لتحسين سرعة التصفح",
      "مكونات تفاعلية ناعمة باستخدام Framer Motion وانتقالات بصرية جذابة",
    ],
    architecture: [
      "Next.js App Router with TypeScript for robust component architecture",
      "Tailwind CSS custom design system tailored for high-end construction aesthetics",
      "i18n internationalization module supporting Arabic and English",
      "Custom YouTube API lazy loader for optimal page speed",
    ],
    architecture_ar: [
      "Next.js App Router مع TypeScript لبناء معمارية قوية",
      "نظام تصميم Tailwind CSS خاص بشركات التشطيبات الفاخرة",
      "وحدة تعريب i18n تدعم اللغتين العربية والإنجليزية",
      "محمل كسول مخصص لمقاطع فيديو YouTube لرفع سرعة الموقع",
    ],
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "TailwindCSS", color: "green-text-gradient" },
      { name: "i18n", color: "pink-text-gradient" },
      { name: "Context", color: "orange-text-gradient" },
    ],
    image: Elshams,
    source_code_link: "https://github.com",
    LiveDemo: "https://shamsfinishing.com",
    isPrivate: true,
  },
  {
    id: "summit-egypt",
    name: "Summit Egypt Real Estate",
    name_ar: "منصة صنيت مصر للعقارات",
    tagline: "Comprehensive Real Estate Marketplace for Egyptian Property Buying & Renting",
    tagline_ar: "منصة عقارية متكاملة لبيع وشراء وإيجار العقارات في مصر",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2023 – 2024",
    year_ar: "2023 – 2024",
    client: "Summit Egypt",
    client_ar: "صنيت إيجيبت",
    category: "fullstack",
    description: "A comprehensive real estate platform for buying and renting properties in Egypt. Features modern UI, property management system, secure payment gateway for deposits, and integrated admin dashboard. Built with React frontend and ASP.NET Core backend for robust performance.",
    description_ar: "منصة عقارية متكاملة لشراء وتأجير العقارات والوحدات السكنية في مصر. واجهة مستخدم عصرية، نظام إدارة عقارات، بوابة دفع إلكتروني لحجز الوحدات ولوحة تحكم للمسؤولين مبنية بـ React و ASP.NET Core.",
    features: [
      "Real Estate Marketplace for Buying and Renting Properties across Egypt",
      "Property Management System with Integrated Admin Dashboard",
      "Secure Payment Gateway for Online Property Deposits & Booking",
      "Robust ASP.NET Core & SQL Server Backend Architecture",
    ],
    features_ar: [
      "سوق عقاري لشراء واستئجار العقارات في مختلف المحافظات المصرية",
      "نظام إدارة العقارات مع لوحة تحكم إدارية متكاملة",
      "بوابة دفع إلكتروني آمنة لمقدمات الحجز والتعاقدات",
      "معمارية خوادم قوية بـ ASP.NET Core وقواعد بيانات SQL Server",
    ],
    architecture: [
      "React frontend with reusable property filter and card components",
      "Bootstrap grid and styling system",
      "ASP.NET Core Web API with clean architecture",
      "Microsoft SQL Server relational database",
    ],
    architecture_ar: [
      "واجهة React مع مكونات فلترة وبطاقات عقارية قابلة لإعادة الاستخدام",
      "نظام تخطيط وتنسيق Bootstrap المتجاوب",
      "خدمات ASP.NET Core Web API بمعمارية نظيفة",
      "قاعدة بيانات SQL Server علائقية متطورة",
    ],
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Bootstrap", color: "green-text-gradient" },
      { name: "Web API", color: "pink-text-gradient" },
      { name: "MVC", color: "orange-text-gradient" },
      { name: "SQL", color: "blue-text-gradient" },
    ],
    image: summit,
    source_code_link: "https://github.com",
    LiveDemo: "https://www.summitegypt.com",
    isPrivate: true,
  },
  {
    id: "afrograins",
    name: "AFROGrains Trading Platform",
    name_ar: "منصة أفروجرينز للتجارة الدولية",
    tagline: "International Commodity Trading Platform for Agricultural Raw Materials",
    tagline_ar: "منصة تجارة دولية للسلع الزراعية والمواد الخام الصناعية",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2023 – 2024",
    year_ar: "2023 – 2024",
    client: "AFROGrains L.L.C",
    client_ar: "أفروجرينز (AFROGrains L.L.C)",
    category: "fullstack",
    description: "International trading platform for AFROGrains L.L.C, specializing in agricultural supplies, fertilizers, and industrial raw materials. Features innovative financial solutions and global trade connections, focusing on African markets since 1977.",
    description_ar: "منصة تجارة دولية لشركة AFROGrains المتخصصة في التوريدات الزراعية والأسمدة والمواد الخام الصناعية في الأسواق الإفريقية والعالمية منذ عام 1977.",
    features: [
      "International B2B Agricultural Commodities Trading Platform",
      "Global Supply Chain Network & Logistics Showcase",
      "B2B Trade Inquiries, Quote Generation & Product Specs",
      "Responsive Multi-Device Interface with Enterprise Styling",
    ],
    features_ar: [
      "منصة تجارة سلع زراعية دولية B2B",
      "استعراض شبكات الإمداد العالمية وسلاسل التوريد واللوجستيات",
      "استقبال طلبات عروض الأسعار والمواصفات الفنية للسلع",
      "واجهة متجاوبة تلائم مختلف الشاشات والأجهزة",
    ],
    architecture: [
      "React.js frontend for high-speed catalog exploration",
      "ASP.NET MVC & Web API for business logic execution",
      "SQL Server database for product categories and inquiries",
      "Bootstrap responsive framework",
    ],
    architecture_ar: [
      "واجهة React.js لتصفح الكتالوج والمنتجات بسرعة فائقة",
      "خوادم ASP.NET MVC و Web API لتنفيذ منطق العمليات",
      "قاعدة بيانات SQL Server لتصنيفات السلع والطلبات",
      "إطار عمل Bootstrap للتصميم المتجاوب",
    ],
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Bootstrap", color: "green-text-gradient" },
      { name: "Web API", color: "pink-text-gradient" },
      { name: "MVC", color: "orange-text-gradient" },
      { name: "SQL", color: "blue-text-gradient" },
    ],
    image: Afro,
    source_code_link: "https://github.com",
    LiveDemo: "https://afrograins.com",
    isPrivate: true,
  },
  {
    id: "alto-company",
    name: "Alto Company Website",
    name_ar: "موقع شركة ألتو للتحليلات وسلاسل الإمداد",
    tagline: "Supply Chain Intelligence & Global Supplier Network Platform",
    tagline_ar: "منصة ذكاء الأعمال وتحليل سلاسل الإمداد وشبكات الموردين العالمية",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2023 – 2024",
    year_ar: "2023 – 2024",
    client: "Alto Technologies",
    client_ar: "ألتو تكنولوجيز (Alto Technologies)",
    category: "fullstack",
    description: "Interactive website for Alto, a supply chain analysis company. Features professional service showcase, business intelligence solutions, and global supplier network integration. Optimized for performance and user experience.",
    description_ar: "موقع تفاعلي لشركة Alto لتحليل سلاسل الإمداد وذكاء الأعمال وربط شبكات الموردين حول العالم، مع تحسين الأداء وسرعة الاستجابة.",
    features: [
      "Supply Chain Analytics & Business Intelligence Platform",
      "Interactive Professional Service Showcase & Global Supplier Network",
      "Optimized Web API Integration with Fast Data Visualization",
      "Clean Enterprise UI Design with High-Speed Response",
    ],
    features_ar: [
      "منصة تحليلات لسلاسل الإمداد وحلول ذكاء الأعمال",
      "استعراض الخدمات الاحترافية وشبكات الموردين الدولية",
      "تكامل مع Web API لعرض وتصوير البيانات البيانية",
      "تصميم مؤسسي نظيف وسرعة استجابة فائقة",
    ],
    architecture: [
      "React.js frontend client with custom data visualization components",
      "ASP.NET Core Web API with high throughput",
      "SQL Server database for business analytics data",
      "Bootstrap layout grid",
    ],
    architecture_ar: [
      "واجهة React.js مع مكونات عرض بيانات مخصصة",
      "ASP.NET Core Web API بقدرة استيعابية عالية",
      "قاعدة بيانات SQL Server لبيانات الأعمال",
      "شبكة تخطيط Bootstrap متجاوبة",
    ],
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Bootstrap", color: "green-text-gradient" },
      { name: "Web API", color: "pink-text-gradient" },
      { name: "MVC", color: "orange-text-gradient" },
      { name: "SQL", color: "blue-text-gradient" },
    ],
    image: Alto,
    source_code_link: "https://github.com",
    LiveDemo: "https://alto-ti.com",
    isPrivate: true,
  },
  {
    id: "aptf-corporate",
    name: "APTF Corporate Website",
    name_ar: "موقع شركة المصنع العربي لتقنية البلاستيك (APTF)",
    tagline: "Bilingual Corporate Platform for Industrial Plastic Manufacturing",
    tagline_ar: "منصة مؤسسية ثنائية اللغة للصناعات البلاستيكية والحلول التقنية",
    role: "Full-Stack Developer",
    role_ar: "مطور برمجيات متكامل (Full-Stack Developer)",
    year: "2023 – 2024",
    year_ar: "2023 – 2024",
    client: "APTF Factory",
    client_ar: "المصنع العربي لتقنية البلاستيك (APTF)",
    category: "fullstack",
    description: "Bilingual corporate website for Arabian Plastic Technology Factory (APTF), showcasing their plastic manufacturing products and services. Features responsive design, detailed product catalogs, and optimized performance.",
    description_ar: "موقع مؤسسي ثنائي اللغة للمصنع العربي لتقنية البلاستيك في المملكة العربية السعودية، لاستعراض منتجات وخدمات تصنيع البلاستيك مع كتالوجات تفصيلية متطورة.",
    features: [
      "Bilingual Corporate Manufacturing Platform for Industrial Plastic Solutions",
      "Comprehensive Digital Product Catalogs & Technical Specifications",
      "Optimized Performance with Responsive Multi-Screen Layouts",
      "Client Inquiry & Quotation Submission Workflow",
    ],
    features_ar: [
      "منصة تصنيع مؤسسية ثنائية اللغة لحلول البلاستيك الصناعي",
      "كتالوجات رقمية متكاملة للمنتجات والمواصفات الفنية",
      "أداء عالي وسرعة تصفح عبر كافة مقاسات الشاشات",
      "مسار تقديم استفسارات العملاء وطلب عروض الأسعار",
    ],
    architecture: [
      "React.js bilingual presentation layer",
      "ASP.NET Web API backend for inquiry processing",
      "SQL Server database management",
      "Bootstrap design tokens",
    ],
    architecture_ar: [
      "طبقة عرض ثنائية اللغة بـ React.js",
      "خوادم ASP.NET Web API لمعالجة الاستفسارات",
      "قاعدة بيانات SQL Server لإدارة البيانات",
      "تصميم متجاوب بـ Bootstrap",
    ],
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Bootstrap", color: "green-text-gradient" },
      { name: "Web API", color: "pink-text-gradient" },
      { name: "MVC", color: "orange-text-gradient" },
      { name: "SQL", color: "blue-text-gradient" },
    ],
    image: APTF,
    source_code_link: "https://github.com",
    LiveDemo: "https://aptf.com.sa",
    isPrivate: true,
  },
];

export const getLocalizedProjects = (lang = 'en') => {
  const isAr = lang === 'ar';
  return projects.map((p) => ({
    ...p,
    name: isAr && p.name_ar ? p.name_ar : p.name,
    tagline: isAr && p.tagline_ar ? p.tagline_ar : p.tagline,
    role: isAr && p.role_ar ? p.role_ar : p.role,
    year: isAr && p.year_ar ? p.year_ar : p.year,
    client: isAr && p.client_ar ? p.client_ar : p.client,
    description: isAr && p.description_ar ? p.description_ar : p.description,
    features: isAr && p.features_ar ? p.features_ar : p.features,
    architecture: isAr && p.architecture_ar ? p.architecture_ar : p.architecture,
  }));
};

export const getLocalizedProject = (idOrSlug, lang = 'en') => {
  const localized = getLocalizedProjects(lang);
  return (
    localized.find((p) => p.id === idOrSlug || p.name.toLowerCase().replace(/\s+/g, '-') === idOrSlug) ||
    localized[0]
  );
};

export { services, technologies, experiences, testimonials, projects };